{{- if and (eq .Values.cluster.hpa "yes") (eq .Values.cluster.deployTo "aks") }}
apiVersion: v1
kind: Secret
metadata:
  name: azure-app-insights-secrets
  namespace: kube-system
type: Opaque
stringData:
  activeDirectoryClientId: {{ .Values.azure_client_id }}
  activeDirectoryClientPassword: {{ .Values.azure_client_secret }}
  applicationInsightsId: {{ .Values.appinsights_appid }}
  tenantId: {{ .Values.azure_tenant_id }}

---

apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-app-insights-trigger-auth
  namespace: kube-system
spec:
  secretTargetRef:
    - parameter: activeDirectoryClientId
      name: azure-app-insights-secrets
      key: activeDirectoryClientId
    - parameter: activeDirectoryClientPassword
      name: azure-app-insights-secrets
      key: activeDirectoryClientPassword
    - parameter: applicationInsightsId
      name: azure-app-insights-secrets
      key: applicationInsightsId
    - parameter: tenantId
      name: azure-app-insights-secrets
      key: tenantId
{{- end }}
